USE MASTER
CREATE DATABASE BIBLIOTERCA_DB
go

USE  BIBLIOTERCA_DB
GO
CREATE TABLE TB_ADMIN  (
ID_ADMIN INT NOT NULL PRIMARY KEY, 
NOM_ADMIN VARCHAR(20)  NOT NULL, 
AP_ADMIN VARCHAR(30) NOT NULL, 
CEL_ADMIN  INT, 
CORREO_ADMIN VARCHAR(60),
CONT INT NOT NULL  
)
GO

-----modificar arriba en tb admin con CONT-ADMIN y la contraseña varchar(30) 
--- VER SI ES NECESARIO PONER LETRAS A LA CONTRASEÑA

USE BIBLIOTERCA_DB
GO
CREATE TABLE TB_VENDEDOR 
(ID_VEND INT NOT NULL PRIMARY KEY,
NOM_VEND VARCHAR (20) NOT NULL, 
AP_VEND VARCHAR (30) NOT NULL, 
CEL_VEND INT, 
CORREO_VEND VARCHAR (60), 
CONT_VEND VARCHAR(30) NOT NULL
)
GO

---clientes 

USE BIBLIOTERCA_DB
GO 

CREATE TABLE TB_CLIENTE
(ID_CLIENT INT NOT NULL  PRIMARY KEY,
NOM_CLIENT VARCHAR(30) NOT NULL, 
AP_CLIENT VARCHAR(60) NOT NULL, 
CEL_CLIENT INT NOT NULL, 
CORREO VARCHAR(80) NOT NULL, 
CONT_CLIENT VARCHAR(30) NOT NULL,
DIR_CLIENT VARCHAR (50)
)
GO


USE BIBLIOTERCA_DB
GO 

CREATE TABLE TB_LIBRO
(ID_LIBRO VARCHAR (10) NOT NULL PRIMARY KEY, 
TIT_LIBRO VARCHAR (60) NOT NULL, 
PREC_LIBRO INT NOT NULL, 
STOCK_LIBRO INT)
GO

USE BIBLIOTERCA_DB
GO 
CREATE TABLE TB_BOLETA
(ID_BOLETA   VARCHAR (8) NOT NULL PRIMARY KEY, 
ID_VEND INT  FOREIGN KEY REFERENCES TB_VENDEDOR(ID_VEND) NOT NULL,
ID_CLIENT INT FOREIGN KEY REFERENCES TB_CLIENTE (ID_CLIENT) NOT NULL,
ID_LIBRO VARCHAR(10) FOREIGN KEY REFERENCES TB_LIBRO (ID_LIBRO) NOT NULL, 
CANT_LIBRO INT NOT NULL, 
COSTO_TOTAL INT NOT NULL)
GO
 

 --- DROPEO 

DROP TABLE TB_ADMIN
DROP TABLE TB_BOLETA
DROP TABLE TB_CLIENTE
DROP TABLE TB_LIBRO
DROP TABLE TB_VENDEDOR

---- VER TABLAS 

SELECT * FROM TB_ADMIN 
SELECT * FROM TB_BOLETA
SELECT * FROM TB_CLIENTE
SELECT * FROM  TB_LIBRO
SELECT * FROM  TB_VENDEDOR


---DROPEAR MI DB
USE MASTER
GO
DROP DATABASE BIBLIOTERCA_DB





